[profile.default]
src = "SmartContracts"
out = "out"
libs = ["lib"]
test = "tests/solidity"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction/=lib/account-abstraction/contracts/"
]
