name: Deploy Azure Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Publish OfflineSyncFunction
        run: dotnet publish Backend/OfflineSyncFunction/OfflineSyncFunction.csproj -c Release -o offline_publish
      - name: Publish RedeemFunction
        run: dotnet publish Backend/RedeemFunction/RedeemFunction.csproj -c Release -o redeem_publish
      - name: Deploy OfflineSyncFunction
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.OFFLINE_FUNCTIONAPP_NAME }}
          package: offline_publish
          publish-profile: ${{ secrets.OFFLINE_FUNCTIONAPP_PUBLISH_PROFILE }}
      - name: Deploy RedeemFunction
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.REDEEM_FUNCTIONAPP_NAME }}
          package: redeem_publish
          publish-profile: ${{ secrets.REDEEM_FUNCTIONAPP_PUBLISH_PROFILE }}
